# Generated by Django 3.2.6 on 2021-08-21 05:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('age', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5)])),
                ('profession', models.CharField(choices=[('Volunteer', 'Volunteer'), ('Organization', 'Organization')], default='Volunteer', max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Profile_photo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('address', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization_Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(choices=[('Volunteer', 'Volunteer'), ('Organization', 'Organization')], default='Organization Official', max_length=500)),
                ('Organization', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Profile_photo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
