# Generated by Django 3.2.6 on 2021-10-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_official',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
