# Generated by Django 3.2.6 on 2021-10-23 05:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0004_auto_20211022_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='roster',
        ),
        migrations.AddField(
            model_name='organization_official',
            name='age',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='organization_official',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='contact',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Volunteer.events'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
