# Generated by Django 3.2.6 on 2021-10-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0005_auto_20211023_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='contact',
            field=models.CharField(default='0000', max_length=1000),
        ),
    ]
