# Generated by Django 3.2.6 on 2021-10-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0006_alter_events_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='event',
        ),
        migrations.AddField(
            model_name='events',
            name='roster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Volunteer.volunteer'),
        ),
        migrations.AlterField(
            model_name='events',
            name='contact',
            field=models.CharField(default='0000000000', max_length=1000),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact',
            field=models.CharField(default='0000000000', max_length=1000),
        ),
    ]
