# Generated by Django 3.2.6 on 2021-10-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0007_auto_20211023_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_official',
            name='contact',
            field=models.CharField(default='0000000000', max_length=1000),
        ),
    ]
