# Generated by Django 3.2.6 on 2021-10-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0008_alter_organization_official_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='roster',
        ),
        migrations.AddField(
            model_name='events',
            name='roster',
            field=models.ManyToManyField(null=True, to='Volunteer.Volunteer'),
        ),
    ]
