# Generated by Django 3.2.6 on 2021-10-23 06:17

import Volunteer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0008_alter_organization_official_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=Volunteer.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='organization_official',
            name='Profile_photo',
            field=models.ImageField(default='posts/avatar.jpg', upload_to=Volunteer.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='Profile_photo',
            field=models.ImageField(default='posts/avatar.jpg', upload_to=Volunteer.models.upload_to, verbose_name='Image'),
        ),
    ]
