# Generated by Django 3.2.6 on 2021-10-23 06:34

import Volunteer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0009_auto_20211023_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_official',
            name='Profile_photo',
            field=models.ImageField(default='profile/avatar.jpg', upload_to=Volunteer.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='Profile_photo',
            field=models.ImageField(default='profile/avatar.jpg', upload_to=Volunteer.models.upload_to, verbose_name='Image'),
        ),
    ]
