# Generated by Django 3.2.6 on 2021-10-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0009_auto_20211023_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='roster',
            field=models.ManyToManyField(null=True, related_name='events', to='Volunteer.Volunteer'),
        ),
    ]
