# Generated by Django 3.2.6 on 2021-10-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0010_alter_events_roster'),
        ('Volunteer', '0010_auto_20211023_1204'),
    ]

    operations = [
    ]
