# Generated by Django 3.2.6 on 2021-10-23 08:51

import Volunteer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0011_merge_20211023_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(default='profile/unnamed.png', upload_to=Volunteer.models.upload_to, verbose_name='Image'),
        ),
    ]
